/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.frontend.view.state.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.frontend.view.state.model.FVSFrontendDataSetEntry;
import com.liferay.frontend.view.state.model.FVSFrontendDataSetEntryModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FVSFrontendDataSetEntry service. Represents a row in the &quot;FVSFrontendDataSetEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FVSFrontendDataSetEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FVSFrontendDataSetEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FVSFrontendDataSetEntryImpl
 * @generated
 */
public class FVSFrontendDataSetEntryModelImpl
	extends BaseModelImpl<FVSFrontendDataSetEntry>
	implements FVSFrontendDataSetEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fvs frontend data set entry model instance should use the <code>FVSFrontendDataSetEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "FVSFrontendDataSetEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"uuid_", Types.VARCHAR},
		{"fvsFrontendDataSetEntryId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"fdsName", Types.VARCHAR},
		{"fvsEntryId", Types.BIGINT}, {"name", Types.VARCHAR},
		{"plid", Types.BIGINT}, {"portletId", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fvsFrontendDataSetEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("fdsName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fvsEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("plid", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("portletId", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FVSFrontendDataSetEntry (mvccVersion LONG default 0 not null,uuid_ VARCHAR(75) null,fvsFrontendDataSetEntryId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,fdsName VARCHAR(75) null,fvsEntryId LONG,name VARCHAR(75) null,plid LONG,portletId VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table FVSFrontendDataSetEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY fvsFrontendDataSetEntry.fvsFrontendDataSetEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY FVSFrontendDataSetEntry.fvsFrontendDataSetEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FDSNAME_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PLID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PORTLETID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FVSFRONTENDDATASETENTRYID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public FVSFrontendDataSetEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _fvsFrontendDataSetEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFvsFrontendDataSetEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _fvsFrontendDataSetEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FVSFrontendDataSetEntry.class;
	}

	@Override
	public String getModelClassName() {
		return FVSFrontendDataSetEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FVSFrontendDataSetEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FVSFrontendDataSetEntry, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FVSFrontendDataSetEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((FVSFrontendDataSetEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FVSFrontendDataSetEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FVSFrontendDataSetEntry, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FVSFrontendDataSetEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FVSFrontendDataSetEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FVSFrontendDataSetEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<FVSFrontendDataSetEntry, Object>>
		_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<FVSFrontendDataSetEntry, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<FVSFrontendDataSetEntry, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<FVSFrontendDataSetEntry, Object>>();
		Map<String, BiConsumer<FVSFrontendDataSetEntry, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<FVSFrontendDataSetEntry, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion", FVSFrontendDataSetEntry::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<FVSFrontendDataSetEntry, Long>)
				FVSFrontendDataSetEntry::setMvccVersion);
		attributeGetterFunctions.put("uuid", FVSFrontendDataSetEntry::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<FVSFrontendDataSetEntry, String>)
				FVSFrontendDataSetEntry::setUuid);
		attributeGetterFunctions.put(
			"fvsFrontendDataSetEntryId",
			FVSFrontendDataSetEntry::getFvsFrontendDataSetEntryId);
		attributeSetterBiConsumers.put(
			"fvsFrontendDataSetEntryId",
			(BiConsumer<FVSFrontendDataSetEntry, Long>)
				FVSFrontendDataSetEntry::setFvsFrontendDataSetEntryId);
		attributeGetterFunctions.put(
			"companyId", FVSFrontendDataSetEntry::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<FVSFrontendDataSetEntry, Long>)
				FVSFrontendDataSetEntry::setCompanyId);
		attributeGetterFunctions.put(
			"userId", FVSFrontendDataSetEntry::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<FVSFrontendDataSetEntry, Long>)
				FVSFrontendDataSetEntry::setUserId);
		attributeGetterFunctions.put(
			"userName", FVSFrontendDataSetEntry::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<FVSFrontendDataSetEntry, String>)
				FVSFrontendDataSetEntry::setUserName);
		attributeGetterFunctions.put(
			"createDate", FVSFrontendDataSetEntry::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<FVSFrontendDataSetEntry, Date>)
				FVSFrontendDataSetEntry::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", FVSFrontendDataSetEntry::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<FVSFrontendDataSetEntry, Date>)
				FVSFrontendDataSetEntry::setModifiedDate);
		attributeGetterFunctions.put(
			"fdsName", FVSFrontendDataSetEntry::getFdsName);
		attributeSetterBiConsumers.put(
			"fdsName",
			(BiConsumer<FVSFrontendDataSetEntry, String>)
				FVSFrontendDataSetEntry::setFdsName);
		attributeGetterFunctions.put(
			"fvsEntryId", FVSFrontendDataSetEntry::getFvsEntryId);
		attributeSetterBiConsumers.put(
			"fvsEntryId",
			(BiConsumer<FVSFrontendDataSetEntry, Long>)
				FVSFrontendDataSetEntry::setFvsEntryId);
		attributeGetterFunctions.put("name", FVSFrontendDataSetEntry::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<FVSFrontendDataSetEntry, String>)
				FVSFrontendDataSetEntry::setName);
		attributeGetterFunctions.put("plid", FVSFrontendDataSetEntry::getPlid);
		attributeSetterBiConsumers.put(
			"plid",
			(BiConsumer<FVSFrontendDataSetEntry, Long>)
				FVSFrontendDataSetEntry::setPlid);
		attributeGetterFunctions.put(
			"portletId", FVSFrontendDataSetEntry::getPortletId);
		attributeSetterBiConsumers.put(
			"portletId",
			(BiConsumer<FVSFrontendDataSetEntry, String>)
				FVSFrontendDataSetEntry::setPortletId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getFvsFrontendDataSetEntryId() {
		return _fvsFrontendDataSetEntryId;
	}

	@Override
	public void setFvsFrontendDataSetEntryId(long fvsFrontendDataSetEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fvsFrontendDataSetEntryId = fvsFrontendDataSetEntryId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getFdsName() {
		if (_fdsName == null) {
			return "";
		}
		else {
			return _fdsName;
		}
	}

	@Override
	public void setFdsName(String fdsName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fdsName = fdsName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalFdsName() {
		return getColumnOriginalValue("fdsName");
	}

	@Override
	public long getFvsEntryId() {
		return _fvsEntryId;
	}

	@Override
	public void setFvsEntryId(long fvsEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fvsEntryId = fvsEntryId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@Override
	public long getPlid() {
		return _plid;
	}

	@Override
	public void setPlid(long plid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_plid = plid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPlid() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("plid"));
	}

	@Override
	public String getPortletId() {
		if (_portletId == null) {
			return "";
		}
		else {
			return _portletId;
		}
	}

	@Override
	public void setPortletId(String portletId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_portletId = portletId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalPortletId() {
		return getColumnOriginalValue("portletId");
	}

	@Override
	public long getContainerModelId() {
		return getFvsFrontendDataSetEntryId();
	}

	@Override
	public void setContainerModelId(long containerModelId) {
		_fvsFrontendDataSetEntryId = containerModelId;
	}

	@Override
	public String getContainerModelName() {
		return String.valueOf(getName());
	}

	@Override
	public long getParentContainerModelId() {
		return 0;
	}

	@Override
	public void setParentContainerModelId(long parentContainerModelId) {
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(FVSFrontendDataSetEntry.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), FVSFrontendDataSetEntry.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FVSFrontendDataSetEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FVSFrontendDataSetEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FVSFrontendDataSetEntryImpl fvsFrontendDataSetEntryImpl =
			new FVSFrontendDataSetEntryImpl();

		fvsFrontendDataSetEntryImpl.setMvccVersion(getMvccVersion());
		fvsFrontendDataSetEntryImpl.setUuid(getUuid());
		fvsFrontendDataSetEntryImpl.setFvsFrontendDataSetEntryId(
			getFvsFrontendDataSetEntryId());
		fvsFrontendDataSetEntryImpl.setCompanyId(getCompanyId());
		fvsFrontendDataSetEntryImpl.setUserId(getUserId());
		fvsFrontendDataSetEntryImpl.setUserName(getUserName());
		fvsFrontendDataSetEntryImpl.setCreateDate(getCreateDate());
		fvsFrontendDataSetEntryImpl.setModifiedDate(getModifiedDate());
		fvsFrontendDataSetEntryImpl.setFdsName(getFdsName());
		fvsFrontendDataSetEntryImpl.setFvsEntryId(getFvsEntryId());
		fvsFrontendDataSetEntryImpl.setName(getName());
		fvsFrontendDataSetEntryImpl.setPlid(getPlid());
		fvsFrontendDataSetEntryImpl.setPortletId(getPortletId());

		fvsFrontendDataSetEntryImpl.resetOriginalValues();

		return fvsFrontendDataSetEntryImpl;
	}

	@Override
	public FVSFrontendDataSetEntry cloneWithOriginalValues() {
		FVSFrontendDataSetEntryImpl fvsFrontendDataSetEntryImpl =
			new FVSFrontendDataSetEntryImpl();

		fvsFrontendDataSetEntryImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		fvsFrontendDataSetEntryImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		fvsFrontendDataSetEntryImpl.setFvsFrontendDataSetEntryId(
			this.<Long>getColumnOriginalValue("fvsFrontendDataSetEntryId"));
		fvsFrontendDataSetEntryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		fvsFrontendDataSetEntryImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		fvsFrontendDataSetEntryImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		fvsFrontendDataSetEntryImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		fvsFrontendDataSetEntryImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		fvsFrontendDataSetEntryImpl.setFdsName(
			this.<String>getColumnOriginalValue("fdsName"));
		fvsFrontendDataSetEntryImpl.setFvsEntryId(
			this.<Long>getColumnOriginalValue("fvsEntryId"));
		fvsFrontendDataSetEntryImpl.setName(
			this.<String>getColumnOriginalValue("name"));
		fvsFrontendDataSetEntryImpl.setPlid(
			this.<Long>getColumnOriginalValue("plid"));
		fvsFrontendDataSetEntryImpl.setPortletId(
			this.<String>getColumnOriginalValue("portletId"));

		return fvsFrontendDataSetEntryImpl;
	}

	@Override
	public int compareTo(FVSFrontendDataSetEntry fvsFrontendDataSetEntry) {
		long primaryKey = fvsFrontendDataSetEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FVSFrontendDataSetEntry)) {
			return false;
		}

		FVSFrontendDataSetEntry fvsFrontendDataSetEntry =
			(FVSFrontendDataSetEntry)object;

		long primaryKey = fvsFrontendDataSetEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FVSFrontendDataSetEntry> toCacheModel() {
		FVSFrontendDataSetEntryCacheModel fvsFrontendDataSetEntryCacheModel =
			new FVSFrontendDataSetEntryCacheModel();

		fvsFrontendDataSetEntryCacheModel.mvccVersion = getMvccVersion();

		fvsFrontendDataSetEntryCacheModel.uuid = getUuid();

		String uuid = fvsFrontendDataSetEntryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			fvsFrontendDataSetEntryCacheModel.uuid = null;
		}

		fvsFrontendDataSetEntryCacheModel.fvsFrontendDataSetEntryId =
			getFvsFrontendDataSetEntryId();

		fvsFrontendDataSetEntryCacheModel.companyId = getCompanyId();

		fvsFrontendDataSetEntryCacheModel.userId = getUserId();

		fvsFrontendDataSetEntryCacheModel.userName = getUserName();

		String userName = fvsFrontendDataSetEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			fvsFrontendDataSetEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			fvsFrontendDataSetEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			fvsFrontendDataSetEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			fvsFrontendDataSetEntryCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			fvsFrontendDataSetEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		fvsFrontendDataSetEntryCacheModel.fdsName = getFdsName();

		String fdsName = fvsFrontendDataSetEntryCacheModel.fdsName;

		if ((fdsName != null) && (fdsName.length() == 0)) {
			fvsFrontendDataSetEntryCacheModel.fdsName = null;
		}

		fvsFrontendDataSetEntryCacheModel.fvsEntryId = getFvsEntryId();

		fvsFrontendDataSetEntryCacheModel.name = getName();

		String name = fvsFrontendDataSetEntryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			fvsFrontendDataSetEntryCacheModel.name = null;
		}

		fvsFrontendDataSetEntryCacheModel.plid = getPlid();

		fvsFrontendDataSetEntryCacheModel.portletId = getPortletId();

		String portletId = fvsFrontendDataSetEntryCacheModel.portletId;

		if ((portletId != null) && (portletId.length() == 0)) {
			fvsFrontendDataSetEntryCacheModel.portletId = null;
		}

		return fvsFrontendDataSetEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FVSFrontendDataSetEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FVSFrontendDataSetEntry, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FVSFrontendDataSetEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(FVSFrontendDataSetEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<FVSFrontendDataSetEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<FVSFrontendDataSetEntry, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FVSFrontendDataSetEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((FVSFrontendDataSetEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, FVSFrontendDataSetEntry>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						FVSFrontendDataSetEntry.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private String _uuid;
	private long _fvsFrontendDataSetEntryId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _fdsName;
	private long _fvsEntryId;
	private String _name;
	private long _plid;
	private String _portletId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<FVSFrontendDataSetEntry, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((FVSFrontendDataSetEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"fvsFrontendDataSetEntryId", _fvsFrontendDataSetEntryId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("fdsName", _fdsName);
		_columnOriginalValues.put("fvsEntryId", _fvsEntryId);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("plid", _plid);
		_columnOriginalValues.put("portletId", _portletId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("uuid_", 2L);

		columnBitmasks.put("fvsFrontendDataSetEntryId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("fdsName", 256L);

		columnBitmasks.put("fvsEntryId", 512L);

		columnBitmasks.put("name", 1024L);

		columnBitmasks.put("plid", 2048L);

		columnBitmasks.put("portletId", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private FVSFrontendDataSetEntry _escapedModel;

}