/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.frontend.view.state.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.frontend.view.state.model.FVSFrontendDataSet;
import com.liferay.frontend.view.state.model.FVSFrontendDataSetModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FVSFrontendDataSet service. Represents a row in the &quot;FVSFrontendDataSet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FVSFrontendDataSetModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FVSFrontendDataSetImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FVSFrontendDataSetImpl
 * @generated
 */
@JSON(strict = true)
public class FVSFrontendDataSetModelImpl
	extends BaseModelImpl<FVSFrontendDataSet>
	implements FVSFrontendDataSetModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fvs frontend data set model instance should use the <code>FVSFrontendDataSet</code> interface instead.
	 */
	public static final String TABLE_NAME = "FVSFrontendDataSet";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"uuid_", Types.VARCHAR},
		{"fvsFrontendDataSetId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"fvsEntryId", Types.BIGINT}, {"fdsName", Types.VARCHAR},
		{"name", Types.VARCHAR}, {"plid", Types.BIGINT},
		{"portletId", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fvsFrontendDataSetId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("fvsEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fdsName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("plid", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("portletId", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FVSFrontendDataSet (mvccVersion LONG default 0 not null,uuid_ VARCHAR(75) null,fvsFrontendDataSetId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,fvsEntryId LONG,fdsName VARCHAR(75) null,name VARCHAR(75) null,plid LONG,portletId VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table FVSFrontendDataSet";

	public static final String ORDER_BY_JPQL =
		" ORDER BY fvsFrontendDataSet.fvsFrontendDataSetId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY FVSFrontendDataSet.fvsFrontendDataSetId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FDSNAME_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PLID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PORTLETID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FVSFRONTENDDATASETID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public FVSFrontendDataSetModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _fvsFrontendDataSetId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFVSFrontendDataSetId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _fvsFrontendDataSetId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FVSFrontendDataSet.class;
	}

	@Override
	public String getModelClassName() {
		return FVSFrontendDataSet.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FVSFrontendDataSet, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FVSFrontendDataSet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FVSFrontendDataSet, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((FVSFrontendDataSet)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FVSFrontendDataSet, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FVSFrontendDataSet, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FVSFrontendDataSet)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FVSFrontendDataSet, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FVSFrontendDataSet, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<FVSFrontendDataSet, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<FVSFrontendDataSet, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<FVSFrontendDataSet, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<FVSFrontendDataSet, Object>>();
		Map<String, BiConsumer<FVSFrontendDataSet, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<FVSFrontendDataSet, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion", FVSFrontendDataSet::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<FVSFrontendDataSet, Long>)
				FVSFrontendDataSet::setMvccVersion);
		attributeGetterFunctions.put("uuid", FVSFrontendDataSet::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<FVSFrontendDataSet, String>)
				FVSFrontendDataSet::setUuid);
		attributeGetterFunctions.put(
			"fvsFrontendDataSetId",
			FVSFrontendDataSet::getFVSFrontendDataSetId);
		attributeSetterBiConsumers.put(
			"fvsFrontendDataSetId",
			(BiConsumer<FVSFrontendDataSet, Long>)
				FVSFrontendDataSet::setFVSFrontendDataSetId);
		attributeGetterFunctions.put(
			"companyId", FVSFrontendDataSet::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<FVSFrontendDataSet, Long>)
				FVSFrontendDataSet::setCompanyId);
		attributeGetterFunctions.put("userId", FVSFrontendDataSet::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<FVSFrontendDataSet, Long>)
				FVSFrontendDataSet::setUserId);
		attributeGetterFunctions.put(
			"userName", FVSFrontendDataSet::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<FVSFrontendDataSet, String>)
				FVSFrontendDataSet::setUserName);
		attributeGetterFunctions.put(
			"createDate", FVSFrontendDataSet::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<FVSFrontendDataSet, Date>)
				FVSFrontendDataSet::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", FVSFrontendDataSet::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<FVSFrontendDataSet, Date>)
				FVSFrontendDataSet::setModifiedDate);
		attributeGetterFunctions.put(
			"fvsEntryId", FVSFrontendDataSet::getFVSEntryId);
		attributeSetterBiConsumers.put(
			"fvsEntryId",
			(BiConsumer<FVSFrontendDataSet, Long>)
				FVSFrontendDataSet::setFVSEntryId);
		attributeGetterFunctions.put("fdsName", FVSFrontendDataSet::getFDSName);
		attributeSetterBiConsumers.put(
			"fdsName",
			(BiConsumer<FVSFrontendDataSet, String>)
				FVSFrontendDataSet::setFDSName);
		attributeGetterFunctions.put("name", FVSFrontendDataSet::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<FVSFrontendDataSet, String>)
				FVSFrontendDataSet::setName);
		attributeGetterFunctions.put("plid", FVSFrontendDataSet::getPlid);
		attributeSetterBiConsumers.put(
			"plid",
			(BiConsumer<FVSFrontendDataSet, Long>)FVSFrontendDataSet::setPlid);
		attributeGetterFunctions.put(
			"portletId", FVSFrontendDataSet::getPortletId);
		attributeSetterBiConsumers.put(
			"portletId",
			(BiConsumer<FVSFrontendDataSet, String>)
				FVSFrontendDataSet::setPortletId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getFVSFrontendDataSetId() {
		return _fvsFrontendDataSetId;
	}

	@Override
	public void setFVSFrontendDataSetId(long fvsFrontendDataSetId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fvsFrontendDataSetId = fvsFrontendDataSetId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getFVSEntryId() {
		return _fvsEntryId;
	}

	@Override
	public void setFVSEntryId(long fvsEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fvsEntryId = fvsEntryId;
	}

	@JSON
	@Override
	public String getFDSName() {
		if (_fdsName == null) {
			return "";
		}
		else {
			return _fdsName;
		}
	}

	@Override
	public void setFDSName(String fdsName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fdsName = fdsName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalFDSName() {
		return getColumnOriginalValue("fdsName");
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public long getPlid() {
		return _plid;
	}

	@Override
	public void setPlid(long plid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_plid = plid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPlid() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("plid"));
	}

	@JSON
	@Override
	public String getPortletId() {
		if (_portletId == null) {
			return "";
		}
		else {
			return _portletId;
		}
	}

	@Override
	public void setPortletId(String portletId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_portletId = portletId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalPortletId() {
		return getColumnOriginalValue("portletId");
	}

	@Override
	public long getContainerModelId() {
		return getFVSFrontendDataSetId();
	}

	@Override
	public void setContainerModelId(long containerModelId) {
		_fvsFrontendDataSetId = containerModelId;
	}

	@Override
	public String getContainerModelName() {
		return String.valueOf(getName());
	}

	@Override
	public long getParentContainerModelId() {
		return 0;
	}

	@Override
	public void setParentContainerModelId(long parentContainerModelId) {
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(FVSFrontendDataSet.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), FVSFrontendDataSet.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FVSFrontendDataSet toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FVSFrontendDataSet>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FVSFrontendDataSetImpl fvsFrontendDataSetImpl =
			new FVSFrontendDataSetImpl();

		fvsFrontendDataSetImpl.setMvccVersion(getMvccVersion());
		fvsFrontendDataSetImpl.setUuid(getUuid());
		fvsFrontendDataSetImpl.setFVSFrontendDataSetId(
			getFVSFrontendDataSetId());
		fvsFrontendDataSetImpl.setCompanyId(getCompanyId());
		fvsFrontendDataSetImpl.setUserId(getUserId());
		fvsFrontendDataSetImpl.setUserName(getUserName());
		fvsFrontendDataSetImpl.setCreateDate(getCreateDate());
		fvsFrontendDataSetImpl.setModifiedDate(getModifiedDate());
		fvsFrontendDataSetImpl.setFVSEntryId(getFVSEntryId());
		fvsFrontendDataSetImpl.setFDSName(getFDSName());
		fvsFrontendDataSetImpl.setName(getName());
		fvsFrontendDataSetImpl.setPlid(getPlid());
		fvsFrontendDataSetImpl.setPortletId(getPortletId());

		fvsFrontendDataSetImpl.resetOriginalValues();

		return fvsFrontendDataSetImpl;
	}

	@Override
	public FVSFrontendDataSet cloneWithOriginalValues() {
		FVSFrontendDataSetImpl fvsFrontendDataSetImpl =
			new FVSFrontendDataSetImpl();

		fvsFrontendDataSetImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		fvsFrontendDataSetImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		fvsFrontendDataSetImpl.setFVSFrontendDataSetId(
			this.<Long>getColumnOriginalValue("fvsFrontendDataSetId"));
		fvsFrontendDataSetImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		fvsFrontendDataSetImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		fvsFrontendDataSetImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		fvsFrontendDataSetImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		fvsFrontendDataSetImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		fvsFrontendDataSetImpl.setFVSEntryId(
			this.<Long>getColumnOriginalValue("fvsEntryId"));
		fvsFrontendDataSetImpl.setFDSName(
			this.<String>getColumnOriginalValue("fdsName"));
		fvsFrontendDataSetImpl.setName(
			this.<String>getColumnOriginalValue("name"));
		fvsFrontendDataSetImpl.setPlid(
			this.<Long>getColumnOriginalValue("plid"));
		fvsFrontendDataSetImpl.setPortletId(
			this.<String>getColumnOriginalValue("portletId"));

		return fvsFrontendDataSetImpl;
	}

	@Override
	public int compareTo(FVSFrontendDataSet fvsFrontendDataSet) {
		long primaryKey = fvsFrontendDataSet.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FVSFrontendDataSet)) {
			return false;
		}

		FVSFrontendDataSet fvsFrontendDataSet = (FVSFrontendDataSet)object;

		long primaryKey = fvsFrontendDataSet.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FVSFrontendDataSet> toCacheModel() {
		FVSFrontendDataSetCacheModel fvsFrontendDataSetCacheModel =
			new FVSFrontendDataSetCacheModel();

		fvsFrontendDataSetCacheModel.mvccVersion = getMvccVersion();

		fvsFrontendDataSetCacheModel.uuid = getUuid();

		String uuid = fvsFrontendDataSetCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			fvsFrontendDataSetCacheModel.uuid = null;
		}

		fvsFrontendDataSetCacheModel.fvsFrontendDataSetId =
			getFVSFrontendDataSetId();

		fvsFrontendDataSetCacheModel.companyId = getCompanyId();

		fvsFrontendDataSetCacheModel.userId = getUserId();

		fvsFrontendDataSetCacheModel.userName = getUserName();

		String userName = fvsFrontendDataSetCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			fvsFrontendDataSetCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			fvsFrontendDataSetCacheModel.createDate = createDate.getTime();
		}
		else {
			fvsFrontendDataSetCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			fvsFrontendDataSetCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			fvsFrontendDataSetCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		fvsFrontendDataSetCacheModel.fvsEntryId = getFVSEntryId();

		fvsFrontendDataSetCacheModel.fdsName = getFDSName();

		String fdsName = fvsFrontendDataSetCacheModel.fdsName;

		if ((fdsName != null) && (fdsName.length() == 0)) {
			fvsFrontendDataSetCacheModel.fdsName = null;
		}

		fvsFrontendDataSetCacheModel.name = getName();

		String name = fvsFrontendDataSetCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			fvsFrontendDataSetCacheModel.name = null;
		}

		fvsFrontendDataSetCacheModel.plid = getPlid();

		fvsFrontendDataSetCacheModel.portletId = getPortletId();

		String portletId = fvsFrontendDataSetCacheModel.portletId;

		if ((portletId != null) && (portletId.length() == 0)) {
			fvsFrontendDataSetCacheModel.portletId = null;
		}

		return fvsFrontendDataSetCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FVSFrontendDataSet, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FVSFrontendDataSet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FVSFrontendDataSet, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(FVSFrontendDataSet)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<FVSFrontendDataSet, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<FVSFrontendDataSet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FVSFrontendDataSet, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((FVSFrontendDataSet)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, FVSFrontendDataSet>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					FVSFrontendDataSet.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private String _uuid;
	private long _fvsFrontendDataSetId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _fvsEntryId;
	private String _fdsName;
	private String _name;
	private long _plid;
	private String _portletId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<FVSFrontendDataSet, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((FVSFrontendDataSet)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"fvsFrontendDataSetId", _fvsFrontendDataSetId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("fvsEntryId", _fvsEntryId);
		_columnOriginalValues.put("fdsName", _fdsName);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("plid", _plid);
		_columnOriginalValues.put("portletId", _portletId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("uuid_", 2L);

		columnBitmasks.put("fvsFrontendDataSetId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("fvsEntryId", 256L);

		columnBitmasks.put("fdsName", 512L);

		columnBitmasks.put("name", 1024L);

		columnBitmasks.put("plid", 2048L);

		columnBitmasks.put("portletId", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private FVSFrontendDataSet _escapedModel;

}