/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

const DEFAULT_LABEL = {
	DATA_SET: 'Sample Data Set',
};

const REL_PREFIX = 'r_dataSet';
const REL_POSTFIX = '_c_dataSetERC';

const DATA_SET_CARDS_SECTIONS_RELATIONSHIP =
	REL_PREFIX + 'CardsSections' + REL_POSTFIX;
const DATA_SET_LIST_SECTIONS_RELATIONSHIP =
	REL_PREFIX + 'ListSections' + REL_POSTFIX;
const DATA_SET_TABLE_SECTIONS_RELATIONSHIP =
	REL_PREFIX + 'TableSections' + REL_POSTFIX;

const DATA_SET_CREATION_ACTIONS_RELATIONSHIP =
	REL_PREFIX + 'CreationActions' + REL_POSTFIX;
const DATA_SET_ITEM_ACTIONS_RELATIONSHIP =
	REL_PREFIX + 'ItemActions' + REL_POSTFIX;

const DATA_SET_DATE_FILTERS_RELATIONSHIP =
	REL_PREFIX + 'DateFilters' + REL_POSTFIX;
const DATA_SET_SELECTION_FILTERS_RELATIONSHIP =
	REL_PREFIX + 'SelectionFilters' + REL_POSTFIX;

const DATA_SET_SORTS_RELATIONSHIP = REL_PREFIX + 'Sorts' + REL_POSTFIX;

export {
	DATA_SET_CARDS_SECTIONS_RELATIONSHIP,
	DATA_SET_CREATION_ACTIONS_RELATIONSHIP,
	DATA_SET_DATE_FILTERS_RELATIONSHIP,
	DATA_SET_ITEM_ACTIONS_RELATIONSHIP,
	DATA_SET_LIST_SECTIONS_RELATIONSHIP,
	DATA_SET_SELECTION_FILTERS_RELATIONSHIP,
	DATA_SET_SORTS_RELATIONSHIP,
	DATA_SET_TABLE_SECTIONS_RELATIONSHIP,
	DEFAULT_LABEL,
};
