/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.frontend.view.state.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.frontend.view.state.model.FVSFrontendDataSet;
import com.liferay.frontend.view.state.service.FVSFrontendDataSetLocalService;
import com.liferay.frontend.view.state.service.FVSFrontendDataSetLocalServiceUtil;
import com.liferay.frontend.view.state.service.persistence.FVSFrontendDataSetPersistence;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the fvs frontend data set local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.frontend.view.state.service.impl.FVSFrontendDataSetLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.frontend.view.state.service.impl.FVSFrontendDataSetLocalServiceImpl
 * @generated
 */
public abstract class FVSFrontendDataSetLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, FVSFrontendDataSetLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>FVSFrontendDataSetLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>FVSFrontendDataSetLocalServiceUtil</code>.
	 */

	/**
	 * Adds the fvs frontend data set to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FVSFrontendDataSetLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param fvsFrontendDataSet the fvs frontend data set
	 * @return the fvs frontend data set that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public FVSFrontendDataSet addFVSFrontendDataSet(
		FVSFrontendDataSet fvsFrontendDataSet) {

		fvsFrontendDataSet.setNew(true);

		return fvsFrontendDataSetPersistence.update(fvsFrontendDataSet);
	}

	/**
	 * Creates a new fvs frontend data set with the primary key. Does not add the fvs frontend data set to the database.
	 *
	 * @param fvsFrontendDataSetId the primary key for the new fvs frontend data set
	 * @return the new fvs frontend data set
	 */
	@Override
	@Transactional(enabled = false)
	public FVSFrontendDataSet createFVSFrontendDataSet(
		long fvsFrontendDataSetId) {

		return fvsFrontendDataSetPersistence.create(fvsFrontendDataSetId);
	}

	/**
	 * Deletes the fvs frontend data set with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FVSFrontendDataSetLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param fvsFrontendDataSetId the primary key of the fvs frontend data set
	 * @return the fvs frontend data set that was removed
	 * @throws PortalException if a fvs frontend data set with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public FVSFrontendDataSet deleteFVSFrontendDataSet(
			long fvsFrontendDataSetId)
		throws PortalException {

		return fvsFrontendDataSetPersistence.remove(fvsFrontendDataSetId);
	}

	/**
	 * Deletes the fvs frontend data set from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FVSFrontendDataSetLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param fvsFrontendDataSet the fvs frontend data set
	 * @return the fvs frontend data set that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public FVSFrontendDataSet deleteFVSFrontendDataSet(
		FVSFrontendDataSet fvsFrontendDataSet) {

		return fvsFrontendDataSetPersistence.remove(fvsFrontendDataSet);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return fvsFrontendDataSetPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			FVSFrontendDataSet.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return fvsFrontendDataSetPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.frontend.view.state.model.impl.FVSFrontendDataSetModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return fvsFrontendDataSetPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.frontend.view.state.model.impl.FVSFrontendDataSetModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return fvsFrontendDataSetPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return fvsFrontendDataSetPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return fvsFrontendDataSetPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public FVSFrontendDataSet fetchFVSFrontendDataSet(
		long fvsFrontendDataSetId) {

		return fvsFrontendDataSetPersistence.fetchByPrimaryKey(
			fvsFrontendDataSetId);
	}

	/**
	 * Returns the fvs frontend data set with the matching UUID and company.
	 *
	 * @param uuid the fvs frontend data set's UUID
	 * @param companyId the primary key of the company
	 * @return the matching fvs frontend data set, or <code>null</code> if a matching fvs frontend data set could not be found
	 */
	@Override
	public FVSFrontendDataSet fetchFVSFrontendDataSetByUuidAndCompanyId(
		String uuid, long companyId) {

		return fvsFrontendDataSetPersistence.fetchByUuid_C_First(
			uuid, companyId, null);
	}

	/**
	 * Returns the fvs frontend data set with the primary key.
	 *
	 * @param fvsFrontendDataSetId the primary key of the fvs frontend data set
	 * @return the fvs frontend data set
	 * @throws PortalException if a fvs frontend data set with the primary key could not be found
	 */
	@Override
	public FVSFrontendDataSet getFVSFrontendDataSet(long fvsFrontendDataSetId)
		throws PortalException {

		return fvsFrontendDataSetPersistence.findByPrimaryKey(
			fvsFrontendDataSetId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			fvsFrontendDataSetLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(FVSFrontendDataSet.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"fvsFrontendDataSetId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			fvsFrontendDataSetLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(FVSFrontendDataSet.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"fvsFrontendDataSetId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			fvsFrontendDataSetLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(FVSFrontendDataSet.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"fvsFrontendDataSetId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<FVSFrontendDataSet>() {

				@Override
				public void performAction(FVSFrontendDataSet fvsFrontendDataSet)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, fvsFrontendDataSet);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(FVSFrontendDataSet.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return fvsFrontendDataSetPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return fvsFrontendDataSetLocalService.deleteFVSFrontendDataSet(
			(FVSFrontendDataSet)persistedModel);
	}

	@Override
	public BasePersistence<FVSFrontendDataSet> getBasePersistence() {
		return fvsFrontendDataSetPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return fvsFrontendDataSetPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns the fvs frontend data set with the matching UUID and company.
	 *
	 * @param uuid the fvs frontend data set's UUID
	 * @param companyId the primary key of the company
	 * @return the matching fvs frontend data set
	 * @throws PortalException if a matching fvs frontend data set could not be found
	 */
	@Override
	public FVSFrontendDataSet getFVSFrontendDataSetByUuidAndCompanyId(
			String uuid, long companyId)
		throws PortalException {

		return fvsFrontendDataSetPersistence.findByUuid_C_First(
			uuid, companyId, null);
	}

	/**
	 * Returns a range of all the fvs frontend data sets.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.frontend.view.state.model.impl.FVSFrontendDataSetModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of fvs frontend data sets
	 * @param end the upper bound of the range of fvs frontend data sets (not inclusive)
	 * @return the range of fvs frontend data sets
	 */
	@Override
	public List<FVSFrontendDataSet> getFVSFrontendDataSets(int start, int end) {
		return fvsFrontendDataSetPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of fvs frontend data sets.
	 *
	 * @return the number of fvs frontend data sets
	 */
	@Override
	public int getFVSFrontendDataSetsCount() {
		return fvsFrontendDataSetPersistence.countAll();
	}

	/**
	 * Updates the fvs frontend data set in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FVSFrontendDataSetLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param fvsFrontendDataSet the fvs frontend data set
	 * @return the fvs frontend data set that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public FVSFrontendDataSet updateFVSFrontendDataSet(
		FVSFrontendDataSet fvsFrontendDataSet) {

		return fvsFrontendDataSetPersistence.update(fvsFrontendDataSet);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			FVSFrontendDataSetLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		fvsFrontendDataSetLocalService =
			(FVSFrontendDataSetLocalService)aopProxy;

		_setLocalServiceUtilService(fvsFrontendDataSetLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return FVSFrontendDataSetLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return FVSFrontendDataSet.class;
	}

	protected String getModelClassName() {
		return FVSFrontendDataSet.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				fvsFrontendDataSetPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		FVSFrontendDataSetLocalService fvsFrontendDataSetLocalService) {

		try {
			Field field =
				FVSFrontendDataSetLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, fvsFrontendDataSetLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	protected FVSFrontendDataSetLocalService fvsFrontendDataSetLocalService;

	@Reference
	protected FVSFrontendDataSetPersistence fvsFrontendDataSetPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

}